// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdieveporrgyizrezuld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkaWV2ZXBvcnJneWl6cmV6dWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3NTEyNjMsImV4cCI6MjA4NjMyNzI2M30.gAJdch8mrjVUgvoL0cuPHXe30SEzenCdrzlS9r1M0WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);